imports:
- path: influxdb-enterprise-byol.jinja

resources:
- name: influxdb-enterprise-byol
  type: influxdb-enterprise-byol.jinja
  properties:
    LICENSE_KEY: a1b2c3d4-xxxx-xxxx-xxxx-xxxxxxxxxxxx
